import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/home";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ToliCodes - Anatoliy D. Zaslavskiy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
      </main>
    </div>
  );
};

export default Home;
